require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

RSpec:
  Language:
    ExampleGroups:
      Regular:
        - context
        - describe
        - wrap_context
      Skipped:
        - xcontext
        - xdescribe
        - xwrap_context
      Focused:
        - fcontext
        - fdescribe
        - fwrap_context
    Includes:
      Examples:
        - finclude_contract
        - finclude_examples
        - fwrap_examples
        - include_contract
        - include_examples
        - wrap_examples
        - xinclude_contract
        - xinclude_examples
        - xwrap_examples

FactoryBot/SyntaxMethods:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  AllowedPatterns:
    - '\A\s*#'
  Max: 80

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - spec/**/*_contract*.rb
    - spec/**/*_factories.rb
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_contract*.rb

RSpec/BeNil:
  Enabled: false

RSpec/Eq:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: example

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NamedSubject:
  Exclude:
    - spec/**/*_contract*.rb

RSpec/NestedGroups:
  Max: 5

RSpecRails/InferredSpecType:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - db/migrate/*
    - spec/**/*

Style/NestedParenthesizedCalls:
  Exclude:
    - spec/**/*
