import {
  Theme,
  defaultTheme,
} from './theme';

export const chiaroscuro: Theme = {
  ...defaultTheme,
  background: 'bg-chiaroscuro-background dark:bg-chiaroscuro-background-dark',
  header: '@headerBase text-chiaroscuro-text-strong dark:text-chiaroscuro-text-strong-dark',
  headerBase: 'font-serif',
  headerDanger: '@headerBase text-chiaroscuro-text-danger-hover dark:text-chiaroscuro-text-danger-hover-dark',
  hr: 'border-chiaroscuro-text-strong dark:border-chiaroscuro-text-strong-dark after:border-chiaroscuro-text-strong after:dark:border-chiaroscuro-text-strong-dark',
  hrMuted: 'border-chiaroscuro-text-muted after:border-chiaroscuro-text-muted',
  link: '@linkBase text-chiaroscuro-link hover:text-chiaroscuro-link-hover dark:hover:text-chiaroscuro-link-hover-dark',
  linkBase: 'hover:underline',
  linkDanger: '@linkBase text-chiaroscuro-text-danger hover:text-chiaroscuro-text-danger-hover dark:text-chiaroscuro-text-danger-dark dark:hover:text-chiaroscuro-text-danger-hover-dark',
  name: 'Chiaroscuro',
  navigationDropdown: 'bg-chiaroscuro-background/75 dark:bg-chiaroscuro-background-dark/75 px-2 text-lg',
  navigationDropdownContainer: 'sm:max-h-6 m-1',
  navigationDropdownLabel: 'font-serif text-chiaroscuro-text-strong dark:text-chiaroscuro-text-strong-dark text-xl',
  navigationDropdownItem: '@headerBase mt-1 first:sm:mt-3',
  navigationDropdownLink: '@linkBase hover:no-underline',
  navigationDropdownLinkDisabled: '@navigationDropdownLink cursor-default select-none text-chiaroscuro-text-muted',
  navigationItem: '@headerBase m-1 text-xl',
  navigationLink: '@linkBase hover:no-underline mx-2',
  navigationLinkDisabled: '@navigationLink cursor-default mx-2 select-none text-chiaroscuro-text-muted',
  subtitle: '@headerBase text-2xl',
  text: '@textBase text-chiaroscuro-text dark:text-chiaroscuro-text-dark',
  textBase: 'font-sans',
  textDanger: '@textBase text-chiaroscuro-text-danger dark:text-chiaroscuro-text-danger-dark',
  textMuted: '@textBase text-chiaroscuro-text-muted',
  title: '@headerBase text-5xl',
};
